services:
  - type: web
    name: attendance-web
    env: python
    buildCommand: "./build.sh"
    startCommand: " making_attendance.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: making_attendance.settings
      - fromGroup: attendance-env
