# Generated by Django 4.2.29 on 2026-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_tier',
            field=models.CharField(choices=[('FREE', 'Free (광고 노출)'), ('PRO', 'Pro (광고 제거/자동화)')], default='FREE', max_length=10, verbose_name='회원 등급'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='구독 종료일'),
        ),
    ]
