# Generated by Django 5.1.5 on 2026-04-14 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_membership_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('imp_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='포트원 번호')),
                ('amount', models.PositiveIntegerField(verbose_name='결제금액')),
                ('status', models.CharField(default='ready', max_length=20, verbose_name='결제상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 로그',
                'verbose_name_plural': '결제 로그 목록',
            },
        ),
    ]
