# Generated by Django 5.1.5 on 2026-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='정기결제 빌링키'),
        ),
    ]
