# Generated by Django 4.2.29 on 2026-04-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_customer_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('code', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 여부')),
            ],
            options={
                'verbose_name': '휴대폰 인증',
                'verbose_name_plural': '휴대폰 인증 목록',
            },
        ),
    ]
