# Generated by Django 4.2.29 on 2026-04-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phoneverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'verbose_name': '인증 코드', 'verbose_name_plural': '인증 코드 목록'},
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
