# Generated by Django 5.1.5 on 2025-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
