# Generated by Django 5.1.5 on 2026-02-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='class_days',
            field=models.CharField(blank=True, help_text='수업 요일을 선택하세요 (예: 월,화,수,목,금)', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='department_times',
            field=models.JSONField(blank=True, help_text='각 부서별 수업 시간을 입력하세요', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='departments',
            field=models.CharField(blank=True, help_text='운영하는 부서를 선택하세요 (예: 1부,2부,3부)', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='vacation_end',
            field=models.DateField(blank=True, help_text='방학 종료일을 선택하세요', null=True, verbose_name='방학 종료일'),
        ),
        migrations.AddField(
            model_name='school',
            name='vacation_start',
            field=models.DateField(blank=True, help_text='방학 시작일을 선택하세요', null=True, verbose_name='방학 시작일'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('출석', '출석'), ('지각', '지각'), ('결석', '결석'), ('취소', '취소')], default='출석', max_length=10),
        ),
    ]
