# Generated by Django 5.1.5 on 2026-02-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_school_class_days_school_department_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='vacation_end',
            field=models.DateField(blank=True, null=True, verbose_name='방학 종료일'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vacation_start',
            field=models.DateField(blank=True, null=True, verbose_name='방학 시작일'),
        ),
    ]
