# Generated by Django 5.1.5 on 2026-02-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_school_vacation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='vacation_end',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vacation_start',
        ),
    ]
