# Generated by Django 5.1.5 on 2026-02-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_school_vacation_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_message', models.TextField(default='{student_name} 학생 출석하였습니다.', verbose_name='출석 시 문자 메시지')),
                ('lateness_message', models.TextField(default='{student_name} 학생 지각하였습니다.', verbose_name='지각 시 문자 메시지')),
                ('absence_message', models.TextField(default='{student_name} 학생 결석하였습니다.', verbose_name='결석 시 문자 메시지')),
                ('class_end_message', models.TextField(default='{student_name} 학생 수업 종료되었습니다.', verbose_name='종료 시 문자 메시지')),
                ('auto_send_class_end_sms', models.BooleanField(default=False, verbose_name='자동 종료 문자 보내기')),
                ('auto_send_lateness_sms', models.BooleanField(default=False, verbose_name='자동 지각 문자 보내기')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
