# Generated by Django 5.1.5 on 2026-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('출석', '출석'), ('지각', '지각'), ('결석', '결석'), ('취소', '취소')], default='출석', max_length=10),
        ),
    ]
