# Generated by Django 5.1.5 on 2026-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_add_waiting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cancel_message',
            field=models.TextField(default='{student_name} 학생 출석이 취소되었습니다.', verbose_name='취소 시 문자 메시지'),
        ),
    ]
