# Generated by Django 5.1.5 on 2026-03-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='absence_message_override',
            field=models.TextField(blank=True, null=True, verbose_name='학교별 결석 문자'),
        ),
        migrations.AddField(
            model_name='school',
            name='attendance_message_override',
            field=models.TextField(blank=True, null=True, verbose_name='학교별 출석 문자'),
        ),
        migrations.AddField(
            model_name='school',
            name='cancel_message_override',
            field=models.TextField(blank=True, null=True, verbose_name='학교별 취소 문자'),
        ),
        migrations.AddField(
            model_name='school',
            name='class_end_message_override',
            field=models.TextField(blank=True, null=True, verbose_name='학교별 종료 문자'),
        ),
        migrations.AddField(
            model_name='school',
            name='lateness_message_override',
            field=models.TextField(blank=True, null=True, verbose_name='학교별 지각 문자'),
        ),
    ]
