# Generated by Django 4.2.29 on 2026-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_unique_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='send_absence_sms',
            field=models.BooleanField(default=True, verbose_name='결석 문자 발송'),
        ),
        migrations.AddField(
            model_name='setting',
            name='send_attendance_sms',
            field=models.BooleanField(default=True, verbose_name='출석 문자 발송'),
        ),
        migrations.AddField(
            model_name='setting',
            name='send_cancel_sms',
            field=models.BooleanField(default=True, verbose_name='취소 문자 발송'),
        ),
        migrations.AddField(
            model_name='setting',
            name='send_class_end_sms',
            field=models.BooleanField(default=True, verbose_name='종료 문자 발송'),
        ),
        migrations.AddField(
            model_name='setting',
            name='send_lateness_sms',
            field=models.BooleanField(default=True, verbose_name='지각 문자 발송'),
        ),
    ]
