# Generated by Django 4.2.29 on 2026-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_setting_send_absence_sms_setting_send_attendance_sms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('출석', '출석'), ('출석(문자x)', '출석(문자x)'), ('지각', '지각'), ('지각(문자x)', '지각(문자x)'), ('결석', '결석'), ('결석(문자x)', '결석(문자x)'), ('취소', '취소'), ('취소(문자x)', '취소(문자x)'), ('종료처리', '종료처리'), ('종료처리(문자x)', '종료처리(문자x)')], default='출석', max_length=20),
        ),
    ]
